

development:
  secret_key_base: your_secret_key_base_here_should_be_at_least_30_characters_long

test:
  secret_key_base: your_secret_key_base_here_should_be_at_least_30_characters_long


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

